// Generated by tools/mapgen.mjs from Natural Earth 110m via world-atlas — do not hand-edit.
// A 104 x 42 dot raster of the world, each land cell tagged with the dashboard's
// own six region buckets. Precomputed at build time so the site ships no mapping
// library and no topology file: the whole world is the two strings below.
// Equirectangular, 84°N to 58°S (Antarctica is cut: no region bucket owns it).
export const MAP_COLS = 104
export const MAP_ROWS = 42
// '.' = ocean; U=US C=Canada E=Europe A=Asia M=Middle East O=Other
export const MAP_REGION_ROWS = [
  '........................CCCCCCCCCCEEEEEEEEEEEEEEE.......................................................',
  '...................CCCC.CCCCCCCCEEEEEEEEEEEEEEE........EEEEE.....A............AAAA......................',
  '................CCCCCC.CCCCCCC.EEEEEEEEEEEEEEEE.....................AAAA.....AAAAAAAA......AAA..........',
  'A.....UU.......CCCCCCCCCCCCCCCCC....EEEEEEEEEE.............EE......AA..AAAAAAAAAAAAAAAAAAAAAAAAA.......A',
  'A...UUUUUUUCCCCCCCCCCCCCCCCCCCCCCC..EEEEEEEEEE..........EEEEEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
  'AAAUUUUUUUUCCCCCCCCCCCCCCCCCC.CCCC..EEEEEE...EEE.......EEEEEEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
  '...UUUUUUUUCCCCCCCCCCCCCCC..CCCCCC...EEE.............EEEEEEEEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
  '.....UUUU..UCCCCCCCCCCCCCC...CCCCC................EE.EEEEEEEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA....',
  '.....UU......UCCCCCCCCCCCCCCCCCCCCCC.............EEE..EEEEEEEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...AA.....',
  '.............CCCCCCCCCCCCCCCCCCCCCCC.............EEEEEEEEEEEEEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...A......',
  '...............CCUUUUUUUUCCCCCCCCC.CC.............EEEEEEEEEEEEEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA..........',
  '................UUUUUUUUUUUUCCCUUCC................EEEEEEEEEEEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.A..........',
  '................UUUUUUUUUUUUUUUU.................EEEE.EEEEEEMMMMAAAAAAAAAAAAAAAAAAAAAAAAAAA.AA..........',
  '................UUUUUUUUUUUUUUU..................EEE..E.EEEMMMMMMMMAAAAAAAAAAAAAAAAAAAAAAA.AA...........',
  '.................UUUUUUUUUUUUU....................OOOOO....E.EMMMMMMMMAAAAAAAAAAAAAAAAA.AAAAA...........',
  '..................UUUUUUUUUUU....................OOOOOOOOOOOMMMMMMMMMMAAAAAAAAAAAAAAAAAA.A..............',
  '..................OOOOOUUUU.U...................OOOOOOOOOOOMMMMMMMMMMMAAAAAAAAAAAAAAAAAA................',
  '...................OOOOO....UO.................OOOOOOOOOOOOMMMMMMMMMMMAAAAAAAAAAAAAAAAAA................',
  '.....................OOO..OOOOO................OOOOOOOOOOOOOOOOMMMMMMM..AAAAAAAAAAAAA.A.................',
  '.....................OOOOOO..O.OO..............OOOOOOOOOOOOOOOOOMMMMM....AAAA..AAAAA..AA................',
  '........................OOOO...................OOOOOOOOOOOOOOOOOMMM......AAA...AAAAA..AA................',
  '..........................OO..OOOOO............OOOOOOOOOOOOOOOOOOOO......AA.....AAAA...AA...............',
  '............................OOOOOOOO............OOOOOOOOOOOOOOOOOOO.......AA....AAA..A.AA...............',
  '.............................OOOOOOOOO...........OOO.OOOOOOOOOOOOO.............AAA..AAA.................',
  '............................OOOOOOOOOO................OOOOOOOOOOOO..............AA.AAAA.AA..............',
  '............................OOOOOOOOOOOOO.............OOOOOOOOOO.................AAAAAAAAAAAAO..........',
  '............................OOOOOOOOOOOOOO.............OOOOOOOOO.................AAAA..A..AAAOOOO.......',
  '.............................OOOOOOOOOOOOO.............OOOOOOOOO...................AAAAAA...AOOO..O.....',
  '.............................OOOOOOOOOOOOO.............OOOOOOOOO..O......................OOO.O..........',
  '..............................OOOOOOOOOOO..............OOOOOOOOOOOO....................OOOOOOO..........',
  '...............................OOOOOOOOOO..............OOOOOOOO.OOO...................OOOOOOOOO....O...O',
  '...............................OOOOOOOOOO...............OOOOOOO.OO..................OOOOOOOOOOOO...O....',
  '...............................OOOOOOOO.................OOOOOO..OO..................OOOOOOOOOOOOO.......',
  '...............................OOOOOOO..................OOOOOO.......................OOOOOOOOOOOO.......',
  '...............................OOOOOOO...................OOOO........................OOOOOOOOOOOO.......',
  '..............................OOOOOO.................................................OO.....OOOO......O.',
  '..............................OOOOOO.........................................................OO.......OO',
  '..............................OOOO............................................................O.....OOO.',
  '..............................OOO...................................................................OO..',
  '..............................OOO.......................................................................',
  '..............................OOO.OO....................................................................',
  '...............................OO.......................................................................',
]
export const MAP_CODE_TO_REGION = {
  U: 'US',
  C: 'Canada',
  E: 'Europe',
  A: 'Asia',
  M: 'Middle East',
  O: 'Other',
}
