// Generated by mapgen.mjs from Natural Earth 110m via world-atlas — do not hand-edit.
// A 104 x 42 dot raster of the world, each land cell tagged with the dashboard's
// own six region buckets. Precomputed at build time so the site ships no mapping
// library and no topology file: the whole world is the two strings below.
export const MAP_COLS = 104
export const MAP_ROWS = 42
// '.' = ocean; U=US C=Canada E=Europe A=Asia M=Middle East O=Other
export const MAP_REGION_ROWS = [
  '....................CC.CCCCCEEEEEEEEEEEEEEEE.........EE.......................AA........................',
  '.................CC.C..CCC.......EEEEEEEEEEE.....................AA.......AAAAAAAA.......AA.A...........',
  '.............CCCCCC..C..CCCC.....EEEEEEEEEE.....................A....A.AAAAAAAAAAAAAAA....AAA...........',
  'AAUUUUUUUCCCCCCCCACAAACCACAACCAAAAAAAAAAAAAAAAAAAAAAAAAAAA..AAAA.A....................................AA',
  'AUUUUUUUUCCCCCCCCCCCCCCCAAACCCAAAAAAAAAAAAAAAAAAAAAAAAAAAA.AA........................................A.A',
  '..UUUUUUUCCCCCCCCCCCCCC...CCC......EE..............EEE..EEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.AAA....',
  '....U.....UCCCCCCCCCCCC....CCCC....................E.E..EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.....A........',
  '............CCCCCCCCCCCCC..CCCCC................E.......EEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.....AA........',
  '.............CCCCCCCCCCCCC.CCCCCC...............EE.EEEEEEEEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...A.........',
  '.............CUUUUUUUUCCCCCCCCC..C..............EEEEEEEEEEEEEAAAAAAAAAAAAAAAAAAAAAAAAAAAAA..............',
  '..............UUUUUUUUUUUUCCCUCC.................EEEEEEEEE.AAAA..AAAAAAAAAAAAAAAAAAAAAAAA...............',
  '..............UUUUUUUUUUUUUUU..................EEE...E.EE....AA..AAAAAAAAAAAAAAAAAAAAAA...A.............',
  '..............UUUUUUUUUUUUUU...................EE......E.MMMMMAA.AAAAAAAAAAAAAAAAAA..A..................',
  '...............UUUUUUUUUUUUU.....................OOOO.......MMMMMMMAAAAAAAAAAAAAAAAA..A.AA..............',
  '................OUUUUUUUUU.....................OOOOOOO.O...MMMMMMMMAAAAAAAAAAAAAAAAA....................',
  '................OOOOUU........................OOOOOOOOOOOMMMMMM.MMMAAAAAAAAAAAAAAAAA....................',
  '..................OOO........................OOOOOOOOOOOOMM.MMMM.MMAAAAAAAAAAAAAAAAA....................',
  '...................OO....OO..................OOOOOOOOOOOOMMM.MMMMMM..AAAAAA.AAAAAA......................',
  '...................OOO.O.....O...............OOOOOOOOOOOOOOO.MMMMM....AAAA..AAAA........................',
  '.....................OOO.....................OOOOOOOOOOOOOOOO.MM.......AA....AAAA.......................',
  '........................O....................OOOOOOOOOOOOOOOOO.........A......AAA.......................',
  '.........................OO.OOOO..............OOOOOOOOOOOOOOOOOO.......AA............A..................',
  '...........................OOOOOO.............OOOO.OOOOOOOOOOOO.........A.....A......A..................',
  '...........................OOOOOOOO.................OOOOOOOOOOO..............A...AA.....................',
  '..........................OOOOOOOOO.................OOOOOOOOOO................A..AA....A................',
  '..........................OOOOOOOOOOOO...............OOOOOOOO..................A..A.A...AAO.............',
  '..........................OOOOOOOOOOOOO..............OOOOOOOO...................AA.......AOO..O.........',
  '...........................OOOOOOOOOOOO..............OOOOOOOO...............................O...........',
  '...........................OOOOOOOOOOO...............OOOOOOOO..O.......................OO.O.............',
  '.............................OOOOOOOOO...............OOOOOOOO.OO.....................OOOO.O.............',
  '.............................OOOOOOOOO...............OOOOOO...O.....................OOOOOOOO............',
  '.............................OOOOOOOO.................OOOOOO..O...................OOOOOOOOOOO...........',
  '.............................OOOOOO...................OOOOO.......................OOOOOOOOOOO...........',
  '.............................OOOOOO...................OOOO........................OOOOOOOOOOO...........',
  '.............................OOOOO.....................OO..........................OO...OOOOO...........',
  '............................OOOOO.........................................................OOO......O....',
  '............................OOOO........................................................................',
  '............................OOO............................................................O......O.....',
  '............................OO..........................................................................',
  '............................OO..........................................................................',
  '............................OO..........................................................................',
  '........................................................................................................'
]
export const MAP_CODE_TO_REGION = {
  U: 'US',
  C: 'Canada',
  E: 'Europe',
  A: 'Asia',
  M: 'Middle East',
  O: 'Other',
}
